# en.yml
en:
  home: "Home"
  about_us: "About Us"
  services: "Services"
  service_1_title: "Personal Training"
  service_1_description: "We offer personal training for your fitness goals."
  photo_gallery: "Photo Gallery"
  testimonials: "What Our Clients Say"
  footer_text: "All Rights Reserved"
  welcome_title: "Welcome to Our Fitness Club"
  welcome_description: "Get fit and stay healthy with us."
  explore_services: "Explore Services"
  read_more: "Read More"
  admin_login: "Admin Login"
  username: "Username"
  password: "Password"
  enter_username: "Enter your username"
  enter_password: "Enter your password"
  remember_me: "Remember me"
  login: "Login"
  forgot_password: "Forgot Password?"


