en:
  about_us: "About Us"
  learn_more_about_us: "Learn more about us"
  our_mission: "Our Mission"
  our_mission_desc: "We are dedicated to providing top-notch fitness and health services."
  our_values: "Our Values"
  value_1: "Excellence in Training"
  value_2: "Commitment to Health"
  value_3: "Community Engagement"
  services: "Services"
  discover_our_services: "Discover our services"
  personal_training: "Personal Training"
  personal_training_desc: "One-on-one personalized fitness programs."
  yoga_classes: "Yoga Classes"
  yoga_classes_desc: "Improve flexibility and relaxation with our yoga sessions."
  pool_training: "Pool Training"
  pool_training_desc: "Get fit in the water with our specialized swimming sessions."
  trainers: "Trainers"
  meet_our_trainers: "Meet our trainers"
  schedule: "Schedule"
  check_our_schedule: "Check our class schedule"
  gallery: "Gallery"
  view_our_gallery: "View our photo gallery"
  contact_us: "Contact Us"
  get_in_touch: "Get in touch with us"
  your_name: "Your Name"
  your_email: "Your Email"
  your_message: "Your Message"
  send_message: "Send Message"
  upload_image: "Upload Image"
  upload: "Upload"
  comments: "Comments"
  your_comment: "Your Comment"
  submit_comment: "Submit Comment"
