uk:
  about_us: "Про нас"
  learn_more_about_us: "Дізнайтесь більше про нас"
  our_mission: "Наша місія"
  our_mission_desc: "Ми прагнемо надавати високоякісні послуги у галузі фітнесу та здоров’я."
  our_values: "Наші цінності"
  value_1: "Відмінність у тренуваннях"
  value_2: "Відданість здоров'ю"
  value_3: "Залучення до громади"
  services: "Послуги"
  discover_our_services: "Ознайомтесь з нашими послугами"
  personal_training: "Персональні тренування"
  personal_training_desc: "Індивідуальні фітнес-програми для кожного."
  yoga_classes: "Заняття йогою"
  yoga_classes_desc: "Покращуйте гнучкість та розслаблення на наших заняттях йогою."
  pool_training: "Тренування у басейні"
  pool_training_desc: "Станьте сильнішими у воді з нашими спеціалізованими плавальними тренуваннями."
  trainers: "Тренери"
  meet_our_trainers: "Познайомтесь з нашими тренерами"
  schedule: "Розклад"
  check_our_schedule: "Перевірте наш розклад занять"
  gallery: "Галерея"
  view_our_gallery: "Перегляньте нашу фотогалерею"
  contact_us: "Контакти"
  get_in_touch: "Зв'яжіться з нами"
  your_name: "Ваше ім'я"
  your_email: "Ваш email"
  your_message: "Ваше повідомлення"
  send_message: "Надіслати повідомлення"
  upload_image: "Завантажити зображення"
  upload: "Завантажити"
  comments: "Коментарі"
  your_comment: "Ваш коментар"
  submit_comment: "Залишити коментар"
