# uk.yml
uk:
  home: "Головна"
  about_us: "Про нас"
  services: "Послуги"
  service_1_title: "Персональні тренування"
  service_1_description: "Ми пропонуємо персональні тренування для досягнення ваших цілей."
  photo_gallery: "Фотогалерея"
  testimonials: "Відгуки наших клієнтів"
  footer_text: "Усі права захищено"
  welcome_title: "Ласкаво просимо до нашого фітнес-клубу"
  welcome_description: "Залишайтеся у формі та будьте здорові разом з нами."
  explore_services: "Досліджуйте послуги"
  read_more: "Читати більше
  admin_login: "Вхід адміністратора"
  username: "Ім'я користувача"
  password: "Пароль"
  enter_username: "Введіть ваше ім'я користувача"
  enter_password: "Введіть ваш пароль"
  remember_me: "Запам'ятати мене"
  login: "Увійти"
  forgot_password: "Забули пароль?"
